# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: MSBuild

on: pull_request

concurrency:
      # Cancel any builds currently in progress for the same PR.
      # Allow running concurrently for with any other commits.
      group: ci-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        configurations: [DebugStandalone]
    runs-on: windows-latest
    env:
      # Path to the solution file relative to the root of the project.
      SOLUTION_FILE_PATH: teep.sln

      # Configuration type to build.
      # You can convert this to a build matrix if you need coverage of multiple configuration types.
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

      BUILD_PLATFORM: x64

    steps:
    # https://stackoverflow.com/questions/65164060/install-nasm-on-github-windows-job
    #- name: Install NASM
    #  run: |
    #    choco install nasm
    #    echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: shogo82148/actions-setup-perl@v1

    - name: Prepare the OpenSSL build directory
      working-directory: ${{github.workspace}}/external/openssl
      run: mkdir _build

    - name: Configure OpenSSL
      working-directory: ${{github.workspace}}/external/openssl/_build
      run: |
        perl ..\Configure --banner=Configured no-makedepend no-deprecated no-asm -DOPENSSL_SMALL_FOOTPRINT VC-WIN64A
        perl configdata.pm --dump

    - name: build
      working-directory: ${{github.workspace}}/external/openssl/_build
      run: nmake # verbose, so no /S here

        #- name: test
        #working-directory: ${{github.workspace}}/external/openssl/_build
        #run: nmake test VERBOSE_FAILURE=yes TESTS=-test_fuzz* HARNESS_JOBS=4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Find OpenSSL
      run: |
        dir "${{env.GITHUB_WORKSPACE}}/external/openssl/_build"

        #- name: Install Open Enclave VSIX
        #run:  |
        #curl -fsSL -o OE.vsix https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-TCPS/vsextensions/OpenEnclaveSDK-VSIX/0.17.37/vspackage
        #VSIXInstaller.exe /q /a "OE.vsix"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} /p:Analysis='True' ${{env.SOLUTION_FILE_PATH}}

    - name: Run Unit Tests
      working-directory: ./bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
      run: ./TeepUnitTest.exe -s
